### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by MELAS007** [chenqingspring/ng-lottie#14]
Dear,

I would like to know if you could help me to know how can I appear disappear the animation when i click on like button in ionic 3?

thanks in advance!

**Comment by makan020518** [comment]
**you can like this **
# when you click button show or hide div

import {Component} from '@angular/core';
@Component({
    selector: 'test',
    template: ` <div  *ngIf = "isShow"></div>
                      <button (click)="isShow()">show or hide</button>`
})

export class TestComponent {
    private isShow = true;
    constructor() {}
    isShow() {
        this.isShow = !this.isShow;
    }
}

**Comment by MELAS007** [comment]
Thank you so much for your help!
It is not a <div></div> but <lottie-animation-view 
    [options]="lottieConfig"
    [width]="300"
    [height]="200"
    (animCreated)="handleAnimation($event)">
</lottie-animation-view>

@makan020518

**Comment by makan020518** [comment]
Do you mean this?
```
TestComponent.ts

import { Component, Input } from '@angular/core';
@Component({
    selector: 'lottie-animation-view',
    template: `<div  *ngIf="isShow">show or hide</div>`
})

export class TestComponent {
    @Input() isShow: boolean = true;
}


TestPage.ts
import {Component} from '@angular/core';

@Component({
     template: ` <lottie-animation-view  [isShow]="isShow"></lottie-animation-view>
                        <button (click)="isShow()">show or hide</button>`
})

export class TestPage {
     private isShow = true;
     constructor() {}

     isShow() {
         this.isShow = !this.isShow;
     }
}

```

**Comment by chenqingspring** [comment]
Thanks for your help! @makan020518 

@MELAS007 You can also use `*ngIf` out of `lottie-animation-view`, and handle the toggle logic in your own component, like the first example makan020518 provided :-)

**Comment by MELAS007** [comment]
@makan020518 Thank you Very much !
