### ISSUE TITLE
Update bodymovin dependency

### ISSUE THREAD

**Issue by timbru31** [chenqingspring/ng-lottie#16]
Hi there 👋 ,

bodymovin is now called lottie-web (https://www.npmjs.com/package/lottie-web and https://github.com/airbnb/lottie-web/blob/master/History.md) and has been bumped to v5. Could you update the dependency of bodymovin to 5.1.3 of lottie-web?

Thanks in advance!

**Comment by chenqingspring** [comment]
Thanks for reminding!  I'll update it soon :-)

**Comment by chenqingspring** [comment]
done in v0.3.1

**Comment by timbru31** [comment]
Thanks a lot ❤️
