### ISSUE TITLE
Breaks Server Side Rendering because of canvas

### ISSUE THREAD

**Issue by marcin-j** [chenqingspring/ng-lottie#22]
Hello there,

```LottieAnimationViewModule``` when imported in app.module and with `platform-server` breaks SSR:

```
  throw new Error("NotYetImplemented");
  ^

Error: NotYetImplemented
    at HTMLCanvasElement.exports.nyi 
```

I think it's because it imports the bodymovin library, which uses canvas, which is not implemented in Domino. Could you fix it or add some configuration option for module, to not use canvas?

**Comment by chenqingspring** [comment]
Which version you use? In recent releases, I replaced `bodymovin` to `lottie-web` which solved SSR issue.

**Comment by marcin-j** [comment]
I'm using newest version from npm repo - 0.3.1. You can easily reproduce it with https://github.com/angular/universal-starter just import  `LottieAnimationViewModule` and error occurs.

**Comment by ftanrisevdi** [comment]
Is there any progress about this problem. I have same issue with ssr
...ERROR TypeError: lottie.loadAnimation is not a function
    at LottieAnimationViewComponent.ngOnInit ...

**Comment by damienwebdev** [comment]
@chenqingspring I'm still seeing the same thing as well. Animations work fine once rendered in browser...

```
ERROR TypeError: lottie.loadAnimation is not a function
    at LottieAnimationViewComponent.ngOnInit (server.js:170002:27)
```

**Comment by damienwebdev** [comment]
See #26 this should resolve your issue @ftanrisevdi

**Comment by damienwebdev** [comment]
@ftanrisevdi @marcin-j is this resolved?

**Comment by ftanrisevdi** [comment]
I am not sure, I just removed the lottie because we decided to use a gif image. 

Thanks for your efforts :)

**Comment by Ilyoskhuja** [comment]
@marcin-j , how do you fix error, I have same error
 ```
throw new Error("NotYetImplemented");
  ^

Error: NotYetImplemented
    at HTMLCanvasElement.exports.nyi
```
but I dont use LottieAnimationViewModule,

**Comment by Ilyoskhuja** [comment]
I have same issue
```

 throw new Error("NotYetImplemented");
  ^

Error: NotYetImplemented
    at HTMLCanvasElement.exports.nyi
```
how can I find which library used canvas
