### ISSUE TITLE
Error on ng build -prod

### ISSUE THREAD

**Issue by johnkim1x4** [chenqingspring/ng-lottie#9]
Hi,
So I have no issues compiling the project for development, but when running `ng build -prod` to deploy I get this error:

```ERROR in vendor.026c3e2abdba0940e77a.bundle.js from UglifyJs
Unexpected token: name (LottieAnimationViewModule) [vendor.026c3e2abdba0940e77a.bundle.js:26365,6]
```

Any help would be appreciated. Thank you.

**Comment by chenqingspring** [comment]
Could you please provide more logs here? I guess it due to uglify in AOT mode..

**Comment by johnkim1x4** [comment]
more logs? that's really the only error I get after I run `ng build`.
I searched google and it says it's related to how uglify doesn't support es6, so I'm just wondering if there's a workaround for that.

**Comment by chenqingspring** [comment]
Please use ng-lottie@0.2.0 which I exported as es5. [Here](https://github.com/chenqingspring/ng-demo) is a demo works with `ng build -prod`

**Comment by johnkim1x4** [comment]
It worked! Thank you!! 👍
